# Generated by Django 5.1.1 on 2026-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stairs", "0002_rename_stair_count_stairs_light_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stairs",
            name="step",
            field=models.SmallIntegerField(default=100),
        ),
    ]
