# Generated by Django 5.1.1 on 2026-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_device_chip_type_alter_device_fun_alter_device_mac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="fun",
        ),
        migrations.AddField(
            model_name="device",
            name="components",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
