# Generated by Django 5.1.1 on 2026-02-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_remove_device_fun_device_components_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceSettings",
        ),
        migrations.RemoveField(
            model_name="device",
            name="components",
        ),
    ]
