# Generated by Django 5.1.1 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0007_delete_devicesettings_remove_device_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="svg_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
