# Generated by Django 5.1.1 on 2026-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0008_device_svg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="used_interfaces",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="device",
            name="used_pins",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
