# Generated by Django 5.1.1 on 2026-02-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0009_device_used_interfaces_device_used_pins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="used_interfaces",
        ),
        migrations.RemoveField(
            model_name="device",
            name="used_pins",
        ),
    ]
