# Generated by Django 5.1.1 on 2026-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0010_remove_device_used_interfaces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
