# Generated by Django 5.1.1 on 2026-02-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0011_alter_device_mac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="pending",
        ),
    ]
