# Generated by Django 5.1.1 on 2026-03-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0013_rfidcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="required_action",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
