# Generated by Django 5.1.1 on 2026-03-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0014_device_required_action"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RfidCard",
        ),
    ]
