# Generated by Django 5.1.1 on 2026-03-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0015_delete_rfidcard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
