import logging

from dispatcher.handlers.base import ActionEventBaseHandler
from dispatcher.command_message.message import CommandMessage
from dispatcher.handlers.enums import Scope, MessageType, MessageDirection
from consumers.device.messages.enum import MessageCommand
from dispatcher.handlers.registry import DISPATCH_DICT
from notifier.message import NotifierMessage

logger = logging.getLogger(__name__)


class ActionEventDispatcher:
    def __init__(
        self,
        registry: dict[
            tuple[Scope, MessageType, MessageDirection, MessageCommand],
            ActionEventBaseHandler,
        ],
    ):
        self.repository = registry

    def dispatch(self, message: CommandMessage) -> list[NotifierMessage]:
        # Build a key from the message metadata to find the correct handler
        key = (
            message.scope,
            message.type,
            message.direction,
            message.command,
        )
        try:
            # Look up the handler for this specific message type
            handler = self.repository[key]
        except KeyError:
            # If no handler is registered for this key, log an error
            # and return an empty DispatchResult (no notifications, no commands)
            logger.error(f"No handler registered for {key}")
            return []

        # Call the handler with the message
        # Handler should return a DispatchResult with:
        # - notifications: NotifierMessages to be sent
        # - commands: additional CommandMessages to be dispatched
        result = handler(message)
        notifications = result.notifications
        commands = result.commands

        # Recursively dispatch any new commands returned by the handler
        for cmd in commands:
            nested_notifications = self.dispatch(cmd)
            # Merge notifications generated by nested commands
            notifications.extend(nested_notifications)

        # Return the original DispatchResult, now including notifications
        # from any nested commands
        return notifications


action_event_dispatcher = ActionEventDispatcher(DISPATCH_DICT)
