# Generated by Django 5.1.1 on 2026-02-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0007_delete_devicesettings_remove_device_components"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peripherals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("state", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peripherals",
                        to="device.device",
                    ),
                ),
            ],
        ),
    ]
