# Generated by Django 5.1.1 on 2026-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peripherals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peripherals",
            name="schema_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
