# Generated by Django 5.1.1 on 2026-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peripherals", "0002_peripherals_schema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peripherals",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
