# Generated by Django 5.1.1 on 2026-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peripherals", "0003_alter_peripherals_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peripherals",
            name="schema_name",
        ),
        migrations.AlterField(
            model_name="peripherals",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
