# Generated by Django 5.1.1 on 2026-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peripherals", "0004_remove_peripherals_schema_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RfidCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "allowed_peripherals",
                    models.ManyToManyField(blank=True, to="peripherals.peripherals"),
                ),
            ],
        ),
    ]
