# Generated by Django 5.1.1 on 2026-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RabbitOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("SENT", "send"),
                            ("DELIVERED", "delivered"),
                            ("FAILED", "failed"),
                            ("TIMEOUT", "timeout"),
                            ("PROCESSED", "processed"),
                            ("EXPIRED", "expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("external_id", models.UUIDField(unique=True)),
                ("exchange", models.CharField(max_length=100)),
                ("routing_key", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouterOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("SENT", "send"),
                            ("DELIVERED", "delivered"),
                            ("FAILED", "failed"),
                            ("TIMEOUT", "timeout"),
                            ("PROCESSED", "processed"),
                            ("EXPIRED", "expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("external_id", models.UUIDField(unique=True)),
                ("router_mac", models.CharField(max_length=17)),
                ("expired_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouterInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("SENT", "send"),
                            ("DELIVERED", "delivered"),
                            ("FAILED", "failed"),
                            ("TIMEOUT", "timeout"),
                            ("PROCESSED", "processed"),
                            ("EXPIRED", "expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("external_id", models.UUIDField(unique=True)),
                ("router_mac", models.CharField(max_length=17)),
                ("home_id", models.IntegerField()),
                ("expired_at", models.DateTimeField()),
            ],
            options={
                "unique_together": {("router_mac", "external_id")},
            },
        ),
    ]
