# Generated by Django 5.1.1 on 2026-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rabbitoutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("SENDING", "sending"),
                    ("DELIVERED", "delivered"),
                    ("FAILED", "failed"),
                    ("TIMEOUT", "timeout"),
                    ("PROCESSED", "processed"),
                    ("EXPIRED", "expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="routerinbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("SENDING", "sending"),
                    ("DELIVERED", "delivered"),
                    ("FAILED", "failed"),
                    ("TIMEOUT", "timeout"),
                    ("PROCESSED", "processed"),
                    ("EXPIRED", "expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="routeroutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("SENDING", "sending"),
                    ("DELIVERED", "delivered"),
                    ("FAILED", "failed"),
                    ("TIMEOUT", "timeout"),
                    ("PROCESSED", "processed"),
                    ("EXPIRED", "expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
