# Generated by Django 5.1.1 on 2026-01-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="camera",
            field=models.ManyToManyField(to="camera.camera"),
        ),
    ]
