# Generated by Django 5.1.1 on 2026-03-10 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0012_remove_device_pending"),
        ("peripherals", "0004_remove_peripherals_schema_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("is_local", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="device.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("extra_settings", models.JSONField(default=dict)),
                ("order", models.IntegerField(default=0)),
                (
                    "peripheral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripherals.peripherals",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="rules.rule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator", models.CharField(max_length=20)),
                ("value", models.CharField(max_length=100)),
                (
                    "peripheral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripherals.peripherals",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="rules.rule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("extra_settings", models.JSONField(default=dict)),
                (
                    "peripheral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peripherals.peripherals",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="rules.rule",
                    ),
                ),
            ],
        ),
    ]
