# Generated by Django 5.1.1 on 2026-03-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ruleaction",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="ruletrigger",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggers",
                to="rules.rule",
            ),
        ),
    ]
