# Generated by Django 5.1.1 on 2026-03-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_alter_rule_name_alter_ruleaction_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulecondition",
            name="event",
            field=models.CharField(default="null", max_length=50),
            preserve_default=False,
        ),
    ]
