# Generated by Django 5.1.1 on 2026-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0003_rulecondition_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulecondition",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="rulecondition",
            name="value",
        ),
        migrations.AddField(
            model_name="rulecondition",
            name="condition",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="rulecondition",
            name="triggered",
            field=models.BooleanField(default=False),
        ),
    ]
